### PR TITLE
Update WhenLoadingTestDataFromACSVFile.java

### PR DESCRIPTION
**Pull request by x-hovo-x**
Added all possible parameters for CSVReader to be able to parse special chars like \n \t ...

### CODE REVIEW

**Comment by wakaleo** [comment]
Sorry to be a pain, but could you submit this pull request to serenity-core? We are not maintaining the old Thucydides code base anymore.

**Comment by x-hovo-x** [comment]
Hi,

to be on safe side, is the following path right one?

serenity-core/core/src/main/java/net/thucydides/core/csv

**Comment by wakaleo** [comment]
Yes, that's the one

**Comment by x-hovo-x** [comment]
created 2 PR.
https://github.com/serenity-bdd/serenity-core/pull/31
https://github.com/serenity-bdd/serenity-core/pull/32

could you please review ?

**Comment by x-hovo-x** [comment]
HI John,

just cloned serenity and can't find changes i did for CSVTestDataSource
class.
is it moved/removed or ?

On 4 March 2015 at 23:34, John Ferguson Smart <notifications@github.com>
wrote:

> Closed #161 <https://github.com/thucydides-webtests/thucydides/pull/161>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thucydides-webtests/thucydides/pull/161#event-246383309>
> .
>



-- 

I look forward to hearing from you soon.

Sincerely,

Hovhannes Asatryan

**Comment by x-hovo-x** [comment]
sorry wrong repo...

On 6 April 2015 at 17:37, Hovo <asatryan@gmail.com> wrote:

> HI John,
>
> just cloned serenity and can't find changes i did for CSVTestDataSource
> class.
> is it moved/removed or ?
>
> On 4 March 2015 at 23:34, John Ferguson Smart <notifications@github.com>
> wrote:
>
>> Closed #161 <https://github.com/thucydides-webtests/thucydides/pull/161>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/thucydides-webtests/thucydides/pull/161#event-246383309>
>> .
>>
>
>
>
> --
>
> I look forward to hearing from you soon.
>
> Sincerely,
>
> Hovhannes Asatryan
>



-- 

I look forward to hearing from you soon.

Sincerely,

Hovhannes Asatryan

**Comment by x-hovo-x** [comment]
Hi John,

just create PR for the integration part for escape char from test data.
could you please have a look and merge if it is ok, or let me know what
should be changed.

thanks in advanced.

On 6 April 2015 at 17:45, Hovo <asatryan@gmail.com> wrote:

> sorry wrong repo...
>
> On 6 April 2015 at 17:37, Hovo <asatryan@gmail.com> wrote:
>
>> HI John,
>>
>> just cloned serenity and can't find changes i did for CSVTestDataSource
>> class.
>> is it moved/removed or ?
>>
>> On 4 March 2015 at 23:34, John Ferguson Smart <notifications@github.com>
>> wrote:
>>
>>> Closed #161 <https://github.com/thucydides-webtests/thucydides/pull/161>
>>> .
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/thucydides-webtests/thucydides/pull/161#event-246383309>
>>> .
>>>
>>
>>
>>
>> --
>>
>> I look forward to hearing from you soon.
>>
>> Sincerely,
>>
>> Hovhannes Asatryan
>>
>
>
>
> --
>
> I look forward to hearing from you soon.
>
> Sincerely,
>
> Hovhannes Asatryan
>



-- 

I look forward to hearing from you soon.

Sincerely,

Hovhannes Asatryan

**Pull request closed without merging**
